# Generated by Django 3.2.6 on 2024-01-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
