# Generated by Django 5.0.1 on 2024-01-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_employee_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='dish',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish'),
        ),
    ]
