# Generated by Django 5.0.1 on 2024-01-31 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdetail_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish'),
        ),
    ]
