# Generated by Django 5.0.1 on 2024-01-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderdetail_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='dish',
        ),
    ]
