# Generated by Django 5.0.1 on 2024-01-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderdetail_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
